/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.employeesystem.views;

//Importing all required components
import javax.swing.JOptionPane;

/**
* @author Krishab Munankarmi
* LMU ID: 23048630
 */
public class EmployeeApp extends javax.swing.JFrame {
    
    // Creation of Objects for Admin and User frame
    AdminFrame AFrame = new AdminFrame();
    UserFrame UFrame = new UserFrame();

    /**
     * Creates new form EmployeeApp
     */
    public EmployeeApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoginForm = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblLoginAppTitle = new javax.swing.JLabel();
        lblLoginImage = new javax.swing.JLabel();
        lblLoginTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtFldUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnForgotPassword = new javax.swing.JButton();
        ckboxPassword = new javax.swing.JCheckBox();
        passfldPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1540, 960));
        setMinimumSize(new java.awt.Dimension(1540, 960));

        pnlLoginForm.setBackground(new java.awt.Color(255, 204, 0));
        pnlLoginForm.setMaximumSize(new java.awt.Dimension(1540, 960));
        pnlLoginForm.setMinimumSize(new java.awt.Dimension(1540, 960));
        pnlLoginForm.setPreferredSize(new java.awt.Dimension(1540, 960));

        pnlLogin.setBackground(new java.awt.Color(0, 102, 204));

        lblLoginAppTitle.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        lblLoginAppTitle.setForeground(new java.awt.Color(255, 204, 0));
        lblLoginAppTitle.setText("Employee Management System");

        lblLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/employeesystem/resources/LogoinLogin.png"))); // NOI18N

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(lblLoginImage)
                .addGap(119, 119, 119))
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblLoginAppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblLoginAppTitle)
                .addGap(119, 119, 119)
                .addComponent(lblLoginImage)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        lblLoginTitle.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(0, 102, 204));
        lblLoginTitle.setText("Log in to your account");

        lblUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 102, 204));
        lblUsername.setText("Username:");

        txtFldUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtFldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldUsernameActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 102, 204));
        lblPassword.setText("Password:");

        btnLogin.setBackground(new java.awt.Color(0, 102, 204));
        btnLogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 204, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnForgotPassword.setBackground(new java.awt.Color(255, 204, 0));
        btnForgotPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnForgotPassword.setForeground(new java.awt.Color(0, 102, 204));
        btnForgotPassword.setText("Forgot your Password?");
        btnForgotPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnForgotPassword.setBorderPainted(false);
        btnForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPasswordActionPerformed(evt);
            }
        });

        ckboxPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        ckboxPassword.setForeground(new java.awt.Color(0, 102, 204));
        ckboxPassword.setText("Show Password");
        ckboxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckboxPasswordActionPerformed(evt);
            }
        });

        passfldPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 0));
        jButton1.setText("Quit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginFormLayout = new javax.swing.GroupLayout(pnlLoginForm);
        pnlLoginForm.setLayout(pnlLoginFormLayout);
        pnlLoginFormLayout.setHorizontalGroup(
            pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginFormLayout.createSequentialGroup()
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFormLayout.createSequentialGroup()
                                .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPassword)
                                    .addComponent(lblUsername)
                                    .addComponent(txtFldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(ckboxPassword))
                                    .addComponent(passfldPassword)
                                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(263, 263, 263))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFormLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginFormLayout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(lblLoginTitle))
                            .addGroup(pnlLoginFormLayout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(208, Short.MAX_VALUE))))
        );
        pnlLoginFormLayout.setVerticalGroup(
            pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFormLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblLoginTitle)
                .addGap(109, 109, 109)
                .addComponent(lblUsername)
                .addGap(18, 18, 18)
                .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passfldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ckboxPassword)
                .addGap(79, 79, 79)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnForgotPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        LoginValidation();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPasswordActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Please contact the Administration to recover your Username and Password","Information",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnForgotPasswordActionPerformed

    private void ckboxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckboxPasswordActionPerformed
        if(ckboxPassword.isSelected()){ //Password hiding 
            passfldPassword.setEchoChar((char) 0);
        }
        else{
            passfldPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ckboxPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        QuitButtonLogic(); //Calling quit button logic method
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeApp().setVisible(true);
            }
        });
    }
    /**
     * Validates user while logging in the system
    */
    
    public void LoginValidation(){ //Validation for logging in as admin or user
        String Username = txtFldUsername.getText();
        String Password = passfldPassword.getText();
        
        if("".equals(Username) || "".equals(Password))
        {
            JOptionPane.showMessageDialog(rootPane,"Username and Password must be entered","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
        if("admin".equals(Username) && "admin".equals(Password)){
            
            AFrame.setVisible(true);
            dispose();
        }
        else if("user".equals(Username) && "user".equals(Password)){
            
            UFrame.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Username or Password is incorrect.","Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }
    
    public void QuitButtonLogic() //Quit button logic
    {
        int choiceofUser =  JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to quit?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(choiceofUser==JOptionPane.YES_OPTION){
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgotPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox ckboxPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblLoginAppTitle;
    private javax.swing.JLabel lblLoginImage;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField passfldPassword;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginForm;
    private javax.swing.JTextField txtFldUsername;
    // End of variables declaration//GEN-END:variables
}
